[sysimage]
exclude=["JET"]
statements_files=[]  # Precompile statements files to be used, relative to the project folder
execution_files=["scripts/precompile/workload.jl"] # Precompile execution files to be used, relative to the project folder